version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - laravel_storage:/var/www/html/storage
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: apache2-foreground

volumes:
  laravel_storage:
